update

diff --git a/.github/workflows/json-build.yml b/.github/workflows/json-build.yml
--- a/.github/workflows/json-build.yml
+++ b/.github/workflows/json-build.yml
@@ -107,26 +107,25 @@ jobs:
           name: ${{ steps.art.outputs.name }}
           compression-level: 0 # The RPMs are already compressed :p
           path: |
-            anda-build/rpm/rpms/*
             anda-build/rpm/srpm/*
 
-      - name: Upload packages to subatomic
-        if: inputs.publish
-        run: |
-          subrepo="${{ matrix.pkg.labels.subrepo }}"
-          subatomic-cli upload --prune \
-            --server https://subatomic.fyralabs.com \
-            --token ${{ secrets.SUBATOMIC_TOKEN }} \
-            terra${{ matrix.version }}${{ matrix.pkg.labels['subrepo'] && '-$subrepo' || '' }} anda-build/rpm/rpms/*
+#      - name: Upload packages to subatomic
+ #       if: inputs.publish
+  #      run: |
+   #       subrepo="${{ matrix.pkg.labels.subrepo }}"
+    #      subatomic-cli upload --prune \
+     #       --server https://subatomic.fyralabs.com \
+      #      --token ${{ secrets.SUBATOMIC_TOKEN }} \
+       #     terra${{ matrix.version }}${{ matrix.pkg.labels['subrepo'] && '-$subrepo' || '' }} anda-build/rpm/rpms/*
 
-      - name: Upload source packages to subatomic
-        if: inputs.publish && matrix.pkg.labels['no_upload_srpms'] != '1'
-        run: |
-          subrepo="${{ matrix.pkg.labels.subrepo }}"
-          subatomic-cli upload --prune \
-            --server https://subatomic.fyralabs.com \
-            --token ${{ secrets.SUBATOMIC_TOKEN }} \
-            terra${{ matrix.version }}${{ matrix.pkg.labels['subrepo'] && '-$subrepo' || '' }}-source anda-build/rpm/srpm/*
+#      - name: Upload source packages to subatomic
+ #       if: inputs.publish && matrix.pkg.labels['no_upload_srpms'] != '1'
+  #      run: |
+   #       subrepo="${{ matrix.pkg.labels.subrepo }}"
+    #      subatomic-cli upload --prune \
+     #       --server https://subatomic.fyralabs.com \
+      #      --token ${{ secrets.SUBATOMIC_TOKEN }} \
+       #     terra${{ matrix.version }}${{ matrix.pkg.labels['subrepo'] && '-$subrepo' || '' }}-source anda-build/rpm/srpm/*
 
       - name: Attest build provenance
         if: inputs.publish
@@ -136,9 +135,9 @@ jobs:
             anda-build/rpm/rpms/*
             anda-build/rpm/srpm/*
 
-      - name: Notify Madoguchi (Success)
-        if: inputs.publish && success()
-        run: ./.github/workflows/mg.sh true "${{matrix.pkg.pkg}}" "${{matrix.version}}" "${{matrix.pkg.arch}}" "${{github.run_id}}" "${{secrets.MADOGUCHI_JWT}}" "$GITHUB_SHA"
-      - name: Notify Madoguchi (Failure)
-        if: inputs.publish && (cancelled() || failure())
-        run: ./.github/workflows/mg.sh false "${{matrix.pkg.pkg}}" "${{matrix.version}}" "${{matrix.pkg.arch}}" "${{github.run_id}}" "${{secrets.MADOGUCHI_JWT}}" "$GITHUB_SHA"
+#      - name: Notify Madoguchi (Success)
+ #       if: inputs.publish && success()
+  #      run: ./.github/workflows/mg.sh true "${{matrix.pkg.pkg}}" "${{matrix.version}}" "${{matrix.pkg.arch}}" "${{github.run_id}}" "${{secrets.MADOGUCHI_JWT}}" "$GITHUB_SHA"
+   #   - name: Notify Madoguchi (Failure)
+    #    if: inputs.publish && (cancelled() || failure())
+     #   run: ./.github/workflows/mg.sh false "${{matrix.pkg.pkg}}" "${{matrix.version}}" "${{matrix.pkg.arch}}" "${{github.run_id}}" "${{secrets.MADOGUCHI_JWT}}" "$GITHUB_SHA"
